### ISSUE TITLE
广东省东莞市东城街道广东省东莞市东城区莴领商业街华莱士对面重庆小面

### ISSUE THREAD

**Issue by yangtianyu92** [PyUnit/pyunit-address#1]
作者大神可以试试这个地址，这个是真实的地址不是我编的。。

**Comment by yangtianyu92** [comment]
这个是不是要Train个模型自动生成啊

**Comment by jtyoui** [comment]
> 作者大神可以试试这个地址，这个是真实的地址不是我编的。。

请问你的需求是什么？

**Comment by yangtianyu92** [comment]
补完地址补到新疆去了…我贴了个大创可贴，应该还可以凑活用。




在2021年01月04日 16:09，弱水三千 写道：

作者大神可以试试这个地址，这个是真实的地址不是我编的。。

请问你的需求是什么？

**Comment by jtyoui** [comment]
> 作者大神可以试试这个地址，这个是真实的地址不是我编的。。

```python
if __name__ == '__main__':
    address.add_vague_text('广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面')  # 不存在的地址需要手动增加
    all_test('广东省东莞市东城街道')
    all_test('广东省东莞市东城区莴领商业街华莱士对面重庆小面')


# 地址 广东省东莞市东城街道
# 补全地址 ['广东省-东莞市-东莞市无县级区划-东城街道']
# 纠错地址 广东省-东莞市-东莞市无县级区划-东城街道
# --------------------------
# 
# 地址 广东省东莞市东城区莴领商业街华莱士对面重庆小面
# 补全地址 ['广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面']
# 纠错地址 广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面
# --------------------------

```

**Comment by yangtianyu92** [comment]
非常感谢🙏




在2021年01月04日 17:22，弱水三千 写道：

作者大神可以试试这个地址，这个是真实的地址不是我编的。。

if__name__=='__main__':
    address.add_vague_text('广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面')  # 不存在的地址需要手动增加all_test('广东省东莞市东城街道')
    all_test('广东省东莞市东城区莴领商业街华莱士对面重庆小面')


# 地址 广东省东莞市东城街道# 补全地址 ['广东省-东莞市-东莞市无县级区划-东城街道']# 纠错地址 广东省-东莞市-东莞市无县级区划-东城街道# --------------------------# # 地址 广东省东莞市东城区莴领商业街华莱士对面重庆小面# 补全地址 ['广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面']# 纠错地址 广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面# --------------------------

**Comment by jtyoui** [comment]
> 非常感谢 在2021年01月04日 17:22，弱水三千 写道： 作者大神可以试试这个地址，这个是真实的地址不是我编的。。 if__name__=='__main__': address.add_vague_text('广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面') # 不存在的地址需要手动增加all_test('广东省东莞市东城街道') all_test('广东省东莞市东城区莴领商业街华莱士对面重庆小面') # 地址 广东省东莞市东城街道# 补全地址 ['广东省-东莞市-东莞市无县级区划-东城街道']# 纠错地址 广东省-东莞市-东莞市无县级区划-东城街道# --------------------------# # 地址 广东省东莞市东城区莴领商业街华莱士对面重庆小面# 补全地址 ['广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面']# 纠错地址 广东省-东莞市-东城区-莴领商业街-华莱士对面重庆小面# -------------------------- — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你重新更新一下库，`pip install pyunit-address==2021.1.4`
