### ISSUE TITLE
识别为空咋回事呀

### ISSUE THREAD

**Issue by fengyikang88** [PyUnit/pyunit-address#3]
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 /Users/mars/Desktop/python源码/flaskProject/address.py
[]
4.982679128646851

代码：
import time
import jieba
# from flask import Flask, request
from pyunit_address import Address, find_address

# app = Flask(__name__)

# address = Address(is_max_address=True)
# address.add_vague_text(['红花岗', '花溪'])  # 加入地址名称
# address.add_vague_text('贵州省-遵义市-遵义县-虾子镇-乐安村-乐石台')  # 加入一串有顺序的地址
# address.add_vague_text('自定义词库.txt')  #

# @app.route('/', methods=['get', 'post'])
def all_test():
    # string_ = '我家在红花岗，你家在贵州贵阳花溪区,他家在贵州省遵义市花溪区'
    # finds = find_address(address, string_)
    # for find in finds:
    #     print()
    #     print('地址', find)
    #     print('补全地址', supplement_address(address, find))
    #     print('纠错地址', correct_address(address, find))
    #     print('--------------------------')
    address = Address(is_max_address=True)

    # 添加词库，可以是一个字符串、可以是列表字符串、可以是词库文件，一个词语占一行
    address.add_vague_text('红花岗')  # 在默认词库上追加地址词库
    address.add_vague_text('贵州省-遵义市-遵义县-虾子镇-乐安村')  # 添加补全地址
    address.add_vague_text(['花溪', '贵州省-遵义市-遵义县-虾子镇-乐安村'])  # 加载词库列表，替换默认词库
    address.add_vague_text('自定义词库.txt')  # 加载词库文件，替换默认词库
    af = find_address(address, '我家在贵州遵义红花岗区')
    print(af)

    # ret = {
    #     'Address': text[3] + text[4] + text[5] + text[6],
    #     'Area': text[2],
    #     'City': text[1],
    #     'Province': text[0],
    #     'name': text[7],
    #     'phone': text[8],
    # }
    # res = {'message': 'success', 'code': 200, 'data': ''}
    # return json.dumps(res, ensure_ascii=False)

if __name__ == '__main__':
    start = time.time()
    all_test()
    print(time.time() - start)

**Comment by jtyoui** [comment]
@fengyikang88 识别什么为空？
